/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuwei_audiodemo_OpenGLPlay */

#ifndef _Included_com_liuwei_audiodemo_OpenGLPlay
#define _Included_com_liuwei_audiodemo_OpenGLPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuwei_audiodemo_OpenGLPlay
 * Method:    play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_liuwei_audiodemo_OpenGLPlay_play
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
