/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <SLES/OpenSLES.h>
/* Header for class com_liuwei_audiodemo_OpenGLActivity */

#ifndef _Included_com_liuwei_audiodemo_OpenGLActivity
#define _Included_com_liuwei_audiodemo_OpenGLActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_liuwei_audiodemo_OpenGLActivity
 * Method:    play
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liuwei_audiodemo_OpenGLActivity_play
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuwei_audiodemo_OpenGLActivity
 * Method:    playStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_liuwei_audiodemo_OpenGLActivity_playStop
        (JNIEnv *, jobject);

/*
 * Class:     com_liuwei_audiodemo_OpenGLActivity
 * Method:    record
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_liuwei_audiodemo_OpenGLActivity_record
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuwei_audiodemo_OpenGLActivity
 * Method:    stopRecod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_liuwei_audiodemo_OpenGLActivity_stopRecod
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
